### ISSUE TITLE
[BUG] 端口无法保存

### ISSUE THREAD

**Issue by ToutyRater** [Cenmrev/V2RayW#2]
感谢你开发了V2RayW，试用了一下很不错。
目前在 v0.0.2版本发现一个问题，当退出 V2RayW 再次打开之后，原来设置好的服务器端口全部被重置成了 10086，望修复。
操作系统： windows 10 x64

**Comment by Cenmrev** [comment]
感谢反馈 bug，尝试修复了下
https://github.com/Cenmrev/V2RayW/releases/tag/v0.0.3

如果还是有问题请继续报告，感谢合作！

**Comment by ToutyRater** [comment]
这个问题已经解决了
