### ISSUE TITLE
希望程序添加开机自动启动

### ISSUE THREAD

**Issue by wjx0912** [Cenmrev/V2RayW#21]
托盘的菜单可以添加‘开机自动启动’，对用户更方便，感谢

另外configw.json都在一行代码中，程序能自己format最好了

**Comment by v-c** [comment]
[https://jingyan.baidu.com/article/90895e0ff3a41f64ec6b0bc3.html](https://jingyan.baidu.com/article/90895e0ff3a41f64ec6b0bc3.html)

**Comment by wjx0912** [comment]
这个看过了。可行，但不方便啊
