### ISSUE TITLE
HTTP 传入协议 UDP 设置问题

### ISSUE THREAD

**Issue by ToutyRater** [Cenmrev/V2RayW#3]
我简单看了一下 V2RayW 生成的配置configw.json，发现 inbound 是这样的：
```javascript
  "inbound": {
    "listen": "127.0.0.1",
    "port": 8080,
    "protocol": "http",
    "settings": {
      "timeout": 0,
      "udp": false
    },
    "allowPassive": false
  }
```
其中的 settings 有一个 udp 项，我没有查证过 HTTP 代理是否支持 UDP，但可以确定的是 V2Ray 的 [HTTP 协议设置](https://www.v2ray.com/chapter_02/protocols/http.html)中只有 timeout 而没有 udp。虽然这样能够正常使用，但我还是觉得这算是一个问题

**Comment by Cenmrev** [comment]
> HTTP/FTP proxies do not support UDP at all (since HTTP/FTP are TCP-based protocols)
[how can we set up Proxy server dealing with UDP packets?](http://stackoverflow.com/questions/20976189/how-can-we-set-up-proxy-server-dealing-with-udp-packets)

这一项对于 http 代理来说是冗余信息，按我的理解 JSON 是个字典数据结构，有多余的无关信息没什么影响。

原本我打算 inbound 用 socks5 的，但我不确定 Windows/IE/Edge 是否支持 socks，所以换成了 http。

**Comment by ToutyRater** [comment]
我明白了。我试过在 V2Ray 中 HTTP 代理有 udp 这么一个键值对确实可以正常运行。
关于 Windows 的系统代理（Internet Explorer Option）是否支持 socks，我也不确定。因为我 Google 过，网上都是说可以的，还有不少教程，但我按那些教程都是连不上网，也有可能是我方法不对。
可以看得出来您应该是基本不使用 Windows，还开发 Windows 的客户端，真是感谢。
