### ISSUE TITLE
0.1.0版打不开 一闪而过

### ISSUE THREAD

**Issue by xzr467706992** [Cenmrev/V2RayW#33]
原来一切正常 后来退出了一次程序 重新打开后 任务栏出现标识 但是鼠标放上去后立即消失 无法进行任何操作 没有日志 没有警告 系统是win10 1803

**Comment by Cenmrev** [comment]
https://github.com/Cenmrev/V2RayW/releases/tag/v0.1.1
我也不知道是怎么回事，要不你试试这个v0.1.1能不能用。

**Comment by xzr467706992** [comment]
@Cenmrev 0.11版不再复现
