### ISSUE TITLE
无法保存设置的解决办法

### ISSUE THREAD

**Issue by sudoghut** [Cenmrev/V2RayW#36]
从某次升级以后，无论做了什么设置（可以在 configw.json 里看到新设置被写入），把 V2RayW 关掉重开之后，之前的设置就会被覆盖掉。给管理员权限也不起作用。

解决方法是，1. 关掉系统托盘中的 V2RayW，2. 删掉目录里面的 configw.json，3,. 清空下面这个目录里面的所以文件夹即可
X:\Users\XXX\AppData\Local\Cenmrev

系统环境：Windows 10 Enterprise 2015 LTSB
系统语言：英文
v2ray 文件目录：Desktop\v2ray
故障版本：v0.1.1

最后感谢 Cenmrev 为 v2ray 的 Windows 用户维护这个 GUI 版本

**Comment by Cenmrev** [comment]
谢谢你提供的方法！
