### ISSUE TITLE
最新的V2RayW有个规则Bug

### ISSUE THREAD

**Issue by DaisukiOshino** [Cenmrev/V2RayW#38]
软件打开的时候 用的是V2Ray规则 商店 网易云音乐无法加载 Spotify可以
系统是Win 10创意者 V2Ray内核是3.35

**Comment by SteveZhu0241** [comment]
同发现这个bug，希望能修复。

**Comment by BlackWaters** [comment]
记得这个是win10的问题。
UWP应用不允许loopback，所以导致商店应用无法加载

**Comment by Cenmrev** [comment]
这个是Windows自己的问题，参见 https://zhuanlan.zhihu.com/p/29989157
