### ISSUE TITLE
请问 V2Ray Rules 和 Global Mode 的区别是什么

### ISSUE THREAD

**Issue by ToutyRater** [Cenmrev/V2RayW#4]
我分别勾选了这两项，然后查看 configw.json，没有发现不一样的地方。还请赐教

**Comment by Cenmrev** [comment]
对于 V2Ray Rules 模式，routing->settings->rules 中会多出以下两条以实现国内国外流量区分。
```json
{
  "type": "chinasites",
  "outboundTag": "direct"
},
{
  "type": "chinaip",
  "outboundTag": "direct"
}
```

**Comment by ToutyRater** [comment]
好的，理解了。谢谢

**Comment by puppet1an** [comment]
> 对于 V2Ray Rules 模式，routing->settings->rules 中会多出以下两条以实现国内国外流量区分。
> 
> ```json
> {
>   "type": "chinasites",
>   "outboundTag": "direct"
> },
> {
>   "type": "chinaip",
>   "outboundTag": "direct"
> }
> ```

请问mac 版在什么地方查看 ？  V2Ray Rules 和 Global Mode 以及 manual mode 到底有什么区别？
