### ISSUE TITLE
windows defender 提示v2rayW文件有木马scarletflash

### ISSUE THREAD

**Issue by tomotomitoma** [Cenmrev/V2RayW#44]
不知道是我单独的情况还是有其他人同样。
![7 _li](https://user-images.githubusercontent.com/47825823/53107813-d3f26c00-3570-11e9-8417-b779258d3fdf.png)

**Comment by tjLEIIQM3** [comment]
这是误报，个人开发的新软件下载数到达一定数量之后就有可能出这个问题。
万恶之源大概是设置全局代理时有修改注册表行为。
等几个月之后，如果还是很多人使用这个软件，
微软或许，没准，说不定会去除这个误报。

**Comment by Cenmrev** [comment]
如楼上。这不是我能控制的，V2RayW的代码都是公开的，二进制文件由第三方平台AppVeyor编译。是否信任V2RayW和AppVeyor由用户决定。
https://github.com/Cenmrev/V2RayW/blob/master/appveyor.yml
