### ISSUE TITLE
缺少机场订阅支持。

### ISSUE THREAD

**Issue by aefan** [Cenmrev/V2RayW#49]
v2ray机场的订阅已经都成熟了，希望考虑下。

**Comment by Cenmrev** [comment]
UI 部分已经做好了 https://github.com/Cenmrev/V2RayW/blob/047d68aef05d021f4a8cda7b5d133d08d2435978/V2RayW/AdvancedWindow.xaml#L26
，等我有空把功能实现了。

**Comment by aefan** [comment]
> UI部分已经做好了
> 
> [V2RayW / V2RayW / AdvancedWindow.xaml](https://github.com/Cenmrev/V2RayW/blob/047d68aef05d021f4a8cda7b5d133d08d2435978/V2RayW/AdvancedWindow.xaml#L26)
> 
> [047d68a中的](/Cenmrev/V2RayW/commit/047d68aef05d021f4a8cda7b5d133d08d2435978) 第26 [行](/Cenmrev/V2RayW/commit/047d68aef05d021f4a8cda7b5d133d08d2435978)
> 
> < TabItem  Header = “ {x：Static res：Strings.Subscription} ”  Visibility = “ Collapsed ” >
> 
> ，等我有空把功能实现了。

那个Pac.js能贴出来给大家参与添加吗？有很多被墙的网址都没被代理，pac.js需要完善。

**Comment by RaymanNg** [comment]
> > UI部分已经做好了
> > [V2RayW / V2RayW / AdvancedWindow.xaml](https://github.com/Cenmrev/V2RayW/blob/047d68aef05d021f4a8cda7b5d133d08d2435978/V2RayW/AdvancedWindow.xaml#L26)
> > [047d68a中的](/Cenmrev/V2RayW/commit/047d68aef05d021f4a8cda7b5d133d08d2435978) 第26 [行](/Cenmrev/V2RayW/commit/047d68aef05d021f4a8cda7b5d133d08d2435978)
> > < TabItem  Header = “ {x：Static res：Strings.Subscription} ”  Visibility = “ Collapsed ” >
> > ，等我有空把功能实现了。
> 
> 那个Pac.js能贴出来给大家参与添加吗？有很多被墙的网址都没被代理，pac.js需要完善。

pac文件应该是在Resource文件夹下吧？
https://github.com/Cenmrev/V2RayW/blob/master/V2RayW/Resources/simplepac.txt.txt

**Comment by xgdgsc** [comment]
现在怎么订阅？
