### ISSUE TITLE
希望可以使用 HTTP 伪装功能

### ISSUE THREAD

**Issue by ToutyRater** [Cenmrev/V2RayW#5]
V2RayW 中的传输设置中 TCP 设置只有连接重用，缺少了V2Ray 的 HTTP 伪装，建议添加。

**Comment by Cenmrev** [comment]
https://github.com/Cenmrev/V2RayW/commit/069d8b58c301d62b45556c2aa6da2cf6d218ad46
增加了非常简单的开启/关闭选项，具体 request 和 response 键值太复杂了，没想好怎么做到 GUI 里，而且我自己也没搞懂那些键值的含义。目前只能用默认值。

**Comment by ToutyRater** [comment]
即使是这样，也十分感谢了。关于 V2Ray 的那些键值是 HTTP 头，[Wikipedia](https://en.wikipedia.org/wiki/List_of_HTTP_header_fields) 有简要的说明。
