### ISSUE TITLE
Windows 10 64bit 下运行无效果

### ISSUE THREAD

**Issue by tinpont** [Cenmrev/V2RayW#8]
windows 10 Pro Version 1607下运行无任何显示，既没有报错，也没有界面，任务管理器显示一下就结束了。

**Comment by 8Bobo8Jun** [comment]
1607同情况。不过我这边闪了一下程序无法在当前Windows版本运行，之后再开也是进程显示1秒然后消失

**Comment by 8Bobo8Jun** [comment]
检查同目录下是否有v2ray-core

**Comment by JonasGao** [comment]
我的也是如此。运行无效果。

同目录下，我有放 v2ray-core。不过文件名并不是 v2ray-core。不知道是否对文件名有限制。

现在的文件名就是 v2ray 的原始名称

**Comment by yyjdelete** [comment]
@Cenmrev 
启动不了的原因估计是因为0.0.6的Release, 里面json.net放成xml了, 没放dll的原因吧

**Comment by maoxs2** [comment]
把0.0.5里的Newtonsoft.Json.dll放进0.0.6文件夹里就能用了
[Newtonsoft.Json.zip](https://github.com/Cenmrev/V2RayW/files/1161319/Newtonsoft.Json.zip)

**Comment by tinpont** [comment]
问题已经解决了，使用最新版的程序无问题。

**Comment by Julyyq** [comment]
我的系统也是windows 10 Pro Version 1607，下载最新的0.0.8，对应的2.4.0的core，服务器有收到正常的请求，但是客户端就是不能正常科学上网。

**Comment by Julyyq** [comment]
然后第二天就打不开了，一闪而过。
